/**
 * src/blocks/factories.ts — block factory helpers per spec §3.
 *
 * Mirrors the planned `import { blocks } from "@opencode-ai/sdk/blocks"` API.
 * Each factory returns a fully-typed RenderBlock with autogenerated keys when
 * not provided.
 *
 * Usage:
 *   import { blocks } from "./blocks/factories.js";
 *   blocks.text({ key: "msg", content: "Hello" })
 *   blocks.statRow([{ label: "Tests", value: 42, variant: "success" }])
 */

import type {
  RenderBlock,
  TextBlock,
  StatRowBlock,
  ProgressBlock,
  CodeBlock,
  ListBlock,
  TableBlock,
  RowBlock,
  CustomBlock,
} from "./types.js";

// ── Key counter for auto-generated keys ─────────────────────────────────────
// v0.7.0+ (audit fix): the counter is now a property of the factory bag
// rather than a module-level mutable. In dev with Hot Module Reload, a
// hot reload re-evaluates this module and produces a FRESH `blocks` object
// with a fresh counter — no collision with stale auto-keys still live in
// caller-side stores. The previous module-level `let _counter` would
// reset on HMR and re-issue keys the caller had already seen.

export const blocks = {
  // Per-bag counter. Each `import` of factories.ts (including HMR) creates
  // a fresh bag → a fresh counter.
  _counter: 0,
  autoKey(prefix: string): string {
    return `${prefix}-auto-${++this._counter}`;
  },

  text(input: { key?: string; content: string; version?: number }): TextBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("text"),
      version: input.version ?? 1,
      type: "text" as const,
      content: input.content,
    };
  },

  statRow(input: {
    key?: string;
    stats: Array<{ label: string; value: string | number; variant?: "default" | "success" | "warning" | "error" | "info" }>;
    version?: number;
  }): StatRowBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("stat"),
      version: input.version ?? 1,
      type: "stat-row" as const,
      stats: input.stats,
    };
  },

  progress(input: {
    key?: string;
    percent: number;
    label?: string;
    variant?: "default" | "success" | "warning" | "error";
    segments?: Array<{ label: string; current: number; max: number }>;
    version?: number;
  }): ProgressBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("prog"),
      version: input.version ?? 1,
      type: "progress" as const,
      percent: input.percent,
      label: input.label,
      variant: input.variant,
      segments: input.segments,
    };
  },

  code(input: {
    key?: string;
    language: string;
    content: string;
    title?: string;
    collapsed?: boolean;
    variant?: "default" | "shell" | "diff";
    version?: number;
  }): CodeBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("code"),
      version: input.version ?? 1,
      type: "code" as const,
      language: input.language,
      content: input.content,
      title: input.title,
      collapsed: input.collapsed,
      variant: input.variant,
    };
  },

  list(input: {
    key?: string;
    variant: "unordered" | "ordered" | "checkbox";
    items: Array<{ text: string; checked?: boolean; description?: string; meta?: string }>;
    version?: number;
  }): ListBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("list"),
      version: input.version ?? 1,
      type: "list" as const,
      variant: input.variant,
      items: input.items,
    };
  },

  table(input: {
    key?: string;
    columns: Array<{ key: string; label: string; align?: "left" | "center" | "right" }>;
    rows: Array<Record<string, string | number | boolean | null>>;
    caption?: string;
    version?: number;
  }): TableBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("tbl"),
      version: input.version ?? 1,
      type: "table" as const,
      columns: input.columns,
      rows: input.rows,
      caption: input.caption,
    };
  },

  row(input: {
    key?: string;
    children: RenderBlock[];
    version?: number;
  }): RowBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("row"),
      version: input.version ?? 1,
      type: "row" as const,
      children: input.children,
    };
  },

  custom(input: {
    key?: string;
    id: string;
    data: Record<string, unknown>;
    fallbackText: string;
    version?: number;
  }): CustomBlock & { key: string; version: number } {
    return {
      key: input.key ?? this.autoKey("custom"),
      version: input.version ?? 1,
      type: "custom" as const,
      id: input.id,
      data: input.data,
      fallbackText: input.fallbackText,
    };
  },
};

export default blocks;
